### ISSUE TITLE
[cms] sidebar does not retain position

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1039]
Steps to reproduce:
1. Close the "blades" for Generators, Materializers, and Selectors.
2. Scroll to a formatter and open it
3. Save & close
4. The right sidebar will now scroll to the top and open the selector blade (which keeping the other two closed?)

**Comment by jhmullen** [comment]
To improve performance, I was removing all cards under the modal from rendering whenever a card was opened. It is this removal/re-adding that causes the scrollbar and collapsing to get wonky.

In a different PR (already merged), I changed the cards to only show abbreviated variable lists on the front, which improved performance. In the current PR #1043 , I realized the pain of re-mounting the cards by drawing them again was causing a new performance hit.

Because PR #1043 no longer hides cards under a modal, the scroll wonkiness is no longer a problem. This will close when that PR is merged.

PR #1043 removes the hiding behavior entirely.
