### ISSUE TITLE
[cms] make search endpoint also match member IDs

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1128]
The idea: a user knows the classification ID for the OEC product they are looking for, and types "010101"

We should also perform our LIKE operation on the IDs of the members.

**Comment by jhmullen** [comment]
This was introduced for datamexico in legacy search in 0.17.1.

For the OEC, which uses deepsearch, the ids need to be ingested via the `keywords` column. That issue is ongoing, and is a deepsearch issue (not a canon-cms one), and is tracked here: https://github.com/Datawheel/oec-site/issues/358

Closing this one
