### ISSUE TITLE
[vizbuilder] white-screen when focusing on member input

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1144]
Using `lapis-api.datausa.io`:
1. Select the "Commute Means" measure
2. Add a grouping for "Transportation Means"
3. Click into the `<input>` box to add a member cut
4. White screen!

<img width="441" alt="Screen Shot 2020-11-30 at 3 44 01 PM" src="https://user-images.githubusercontent.com/1847581/100662888-80a37500-3323-11eb-84ff-684c0c28bad8.png">

<img width="811" alt="Screen Shot 2020-11-30 at 3 44 57 PM" src="https://user-images.githubusercontent.com/1847581/100662895-8305cf00-3323-11eb-9eac-de1c44d6e997.png">

**Comment by frabarz** [comment]
This seems to be an issue with the data ingested and how Mondrian handles it.
It seems some members in the last level are not associated to a parent level member. Seen from the other side, the children for some members skip a level.
This is a diagram of the current structure:
![image](https://user-images.githubusercontent.com/11713191/101920613-cb867d80-3baa-11eb-9fc5-51c3fd6f0e77.png)
It seems like Mondrian, even if these level skips happen, can handle the relationship from parents to children (through the `children` property), but cannot from children to parents (through the `ancestors` property).
The failing react component uses the `ancestors` property to build the hierarchy tree, so we have two options: restructure the levels, or rewire the component to use children instead.
I'd vote for the second approach, because tesseract has no support for `ancestors`. It actually doesn't have support for `children` either, but as a feature it's easier to simulate making multiple requests for the members of each level in the grouping/dimension.

**Comment by davelandry** [comment]
2nd approach sounds good to me 👍

**Comment by jhmullen** [comment]
@frabarz  Is this still active?

**Comment by davelandry** [comment]
@jhmullen since we're not going to be supporting the canon-vizbuilder anymore, I would suggest we close this issue

**Comment by davelandry** [comment]
Closing all `[vizbuilder]` issues, as the canon-vizbuilder package is no longer in development in favor of the more generic https://github.com/datawheel/vizbuilder package
