### ISSUE TITLE
replace AreaLoading with components/Loading

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#127]
Currently, the custom `AreaLoading` component does not have it's title and description localized. Looking into this, it appears the component has the same functionality as the `app/components/Loading` component that every canon project is required to have. 

`import Loading from "components/Loading";` should work, as canon looks inside of the `app/` directory for component imports;

**Comment by frabarz** [comment]
This will need a modification and a clarification for future implementations of the Loading component.

The Loading component currently bundled in canon takes its parameters from the overall loading state kept in redux. To allow the component to receive the values from its attributes, the `mapStateToProps` function must be set to handle `(state, ownProps)` as arguments instead of only `(state)`, make it return the value from `ownProps` if set, else from `state`.

**Comment by davelandry** [comment]
@frabarz great catch. I knew if couldn't be that easy...

I've made an issue for modifying the default behavior [here](#129). Make that correction on the same branch as this request and send over the PR!
