### ISSUE TITLE
[cms] unable to add Flickr image to local db

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1275]
Steps to reproduce:
* visit https://dev.cfc.datawheel.us/cms?tab=metadata
* click "add image"
* click "search Flickr"
* click "search"
* wait for images to load
* click on an image
* wait for image to process
* get "Success!" toast
* no changes made to postgres database, no browser console errors, no server errors even when enabling `CANON_CMS_LOGGING`

https://user-images.githubusercontent.com/1847581/138096255-119ff642-f275-484c-aca8-3fee24daa253.mov

**Comment by davelandry** [comment]
Seems that local image uploads are also not working for us. I tried uploading a JPG, it wrote a row to the database but didn't store any blob content:

<img width="969" alt="Screen Shot 2021-11-02 at 9 36 38 AM" src="https://user-images.githubusercontent.com/1847581/139857438-2f0b3b87-f882-4e24-9e97-144afa10018b.png">

**Comment by jhmullen** [comment]
The problem here was a known CANON issue that I failed to fix - even if you aren't using s3 you must set the `CANON_CONST_STORAGE_BUCKET` variable.

I set it to `xxx` and redeployed and made this issue: https://github.com/Datawheel/canon/issues/1282

I will allow you to decide if this can be closed, @davelandry .
