### ISSUE TITLE
[vizbuilder] some state charts appear blank on first load

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#170]
...but after switching the timeline, the current year is viewable. The Data USA measure "Number of Families Receiving Rental Assistance" shows this behavior reliably:

<img width="1261" alt="screen shot 2018-09-19 at 4 10 11 pm" src="https://user-images.githubusercontent.com/1847581/45778409-858a1b80-bc26-11e8-9817-76d6c6b6d21c.png">

**Comment by cnavarreteliz** [comment]
I was switching visualizations in the VizBuilder (VB) and I found that the last selected year is persistent in the next visualization. Indeed, if we pass from "Average Year" (last year 2016) to "Number of Families Receiving Rental Assistance" (last year 2015) we can see the bug. But if we passed from a measure with year 2014 to "Number of...", the selected year is 2014.

So, I think this issue is more related with d3plus than VB. I'm going to explore more deeply the code in VB.
