### ISSUE TITLE
[vizbuilder] specific measure config persists to other measures

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#258]
https://gila-cliff.datausa.io/visualize

1. See the blue map of the US
2. Switch to "Opioids"
3. See the red map
4. Switch back to another measure (like "Total Population")
5. The map persists as red (it should be blue like before)

**Comment by frabarz** [comment]
I tested using devtools breakpoints, and found this is a bug introduced by `d3plus-geomap`.

After some exploring, I noticed the object being passed to the `config` attribute was being modified, so I focused on the root object. First I stopped the execution right before the first render of the `Visualize` component, and saved the color array directly from the exported `colors.json` object:
![image](https://user-images.githubusercontent.com/11713191/47700289-baf63180-dbf4-11e8-914a-931f2267e0a0.png)

Then I ran the steps above, and saved the array again.
![image](https://user-images.githubusercontent.com/11713191/47700383-03155400-dbf5-11e8-81cd-2ab4095ddd7e.png)

Finally, I compared both arrays directly. Both were the same array. Looking at the contents of the first array, I found it was modified:
![image](https://user-images.githubusercontent.com/11713191/47700458-4cfe3a00-dbf5-11e8-9ad2-841c007a4cc3.png)

After more fiddling, I found the modification it's caused on `d3plus-react.Viz.renderViz`, when `assign`ing `globalConfig` with the current `config`.
![image](https://user-images.githubusercontent.com/11713191/47701875-03fcb480-dbfa-11e8-8736-723da89143ba.png)

`assign` is replacing one by one the values of the array, set by `globalConfig`, with the values of the new `config`, set when changing the Measure.
![image](https://user-images.githubusercontent.com/11713191/47702035-7f5e6600-dbfa-11e8-99de-c1abc8925353.png)

**Comment by davelandry** [comment]
That logic actually does make sense, but in the case of what is being passed to d3plus-react from vizbuilder, `config` is actually `config + measureConfig`, correct? That means that if the user of vizbuilder has defined a colorScale in the `config` prop of Vizbuilder, it should fall back to those values if there is no `measureConfig` set up? Here is a code example:

```jsx
<Vizbuilder
  src="https://hovenweep-api.datausa.io/"
  measureConfig={{
    "Opioids": {
      colorScaleConfig: {
        color: "red"
      }
    }
  }}
  config={{
    colorScaleConfig: {
      color: "blue"
    }
  }} />
```

In that case, the "Opioids" color should override the default config color for that measure, but when constructing the `config` to pass to d3plus-react for other measures, it should be passing "blue" to d3plus-react.

**Comment by frabarz** [comment]
Yeah, that's exactly how it's set to work, but that's not the problem in this issue.

In the implementation of the `Visualize.jsx` page, you're setting the value of the color property in the config as a list of colors from an external json file, packed by webpack as an array. The config object passed as a prop is remade on each `Visualize.render`, but this specific color property in the config always points to the same array in the memory. This array is the same array stored in the general configuration for d3plus, because is set in line 124 of d3plus.js. Therefore, in the screenshot of `d3plus-react.Viz.renderViz`, `globalconfig` contains a `colorScaleConfig.color` property pointing to this same array.

Now, `assign` is modifying this array when the user selects the "Opioids" measure, because it's combining the values set in `config.colorScaleConfig.color`, inherited from `measureConfig`, into `globalConfig.colorScaleConfig.color`, our array. So after this, the array is the same, but its contents are now the red strings instead of the original blue ones. Then, going back to the "Total population" measure, `Visualize.render` remakes the config again, but reuses the same array that now contains different values, so there's nothing Vizbuilder can do, since that's the intended behavior.

The solution for this is making `assign` create a new array and do the combination to it instead of combining new values to an old array. It's basically make it do the same as when we use `assign({}, object1, object2)`, but specifically for arrays.

**Comment by davelandry** [comment]
closed with https://github.com/d3plus/d3plus-common/releases/tag/v0.6.44
