### ISSUE TITLE
[vizbuilder] console error when adding 2nd large grouping

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#277]
1. http://localhost:3300/visualize?groups=0-z9TnC&measure=1qWfo
2. Add a new grouping for "Detailed Occupation"
3. Wait...
4. Charts appear the same as previous, but with the following error in console:

<img width="830" alt="screen shot 2018-11-08 at 12 51 26 pm" src="https://user-images.githubusercontent.com/1847581/48217326-1216a780-e355-11e8-8fd1-8d4a28b12dd7.png">

**Comment by frabarz** [comment]
I tried to replicate this, but got a TooMuchData exception before reaching that other error (that error comes from composePropertyName, that is called during rendering after the data has been saved)

**Comment by davelandry** [comment]
Sorry, I shouldn't have posted "localhost", it's happening here: https://katahdin.datausa.io/visualize?groups=0-z9TnC&measure=1qWfo

@frabarz can you help me figure out what's different about the Data USA usage? Here's where we mount the component: https://github.com/DataUSA/datausa-site/blob/canon/app/pages/Visualize.jsx

**Comment by frabarz** [comment]
alright, found the cause: the error happens when you try to build the slug in the onChange hooked function in Visualize.jsx
When a new group is added to the query, the group object is created and put in the array, but internally its `level` property is undefined. Internally Vizbuilder ignores groups whose `level` property is undefined, including when the state history is compared to call the `onChange` hook.
As the new query fails due to the TooMuchData error, the state is returned to the state before the user selects the "Detailed Occupation" level, and in this state the `group.level` property is undefined again, but since the state effectively changed (the group was valid and then it was not), `onChange` is called.

**Comment by davelandry** [comment]
You're my hero @frabarz! Great job investigating this. I've already pushed the fix to the main Data USA repo.
