### ISSUE TITLE
[vizbuilder] modify LinePlot cutoff behavior to show top 10 when there are too many

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#296]
https://joshua-tree.datausa.io/visualize?groups=0-Zam5D&measure=Z1gCJfh

**Comment by frabarz** [comment]
these are caused because some data combinations don't pass the list of conditions for charts
to explain it shortly: the `visualizations` array is the list of available charts, we check the query conditions and remove the charts that shouldn't be shown, the list of visualizations ends up empty

**Comment by davelandry** [comment]
I understand that, but why exactly are we not able to see any visualizations here? Is it because we limit the number of items to be drawn in a line chart? I would expect to see a line chart over time with a line for each university.

**Comment by frabarz** [comment]
For this specific case, linecharts are removed because there would be 3840 lines drawn. The rule we set was to hide linechart for more than 60 lines.
If you limit the members for the grouping to a reasonable number, the charts [appear again](https://joshua-tree.datausa.io/visualize?groups=0-Zam5D-100760~101648~109350~111939~173805~175157~176169&measure=Z1gCJfh).
