### ISSUE TITLE
[CMS] Extend Percentage Bar with complex show/hide sorting

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#386]
Certain charts have a fairly complex requirement.  When collapsed, they need behavior like this:

![image](https://user-images.githubusercontent.com/1714292/50568935-8b64c200-0d28-11e9-83e2-7c9d655c36e3.png)

Note:
- An interstitial of text at an arbitrary cutoff point that changes on show/hide
- Automatic (?) selection of an arbitrary number of "similar" groupBys

After expanding, it needs to look like this:

![image](https://user-images.githubusercontent.com/1714292/50568980-5e64df00-0d29-11e9-867b-11bb54954fa7.png)

Note:
- The interstitial text has changed
- More importantly, the __overall sorting__ has changed. Do we need a different `dataFormat` for the collapsed / uncollapsed versions?

@davelandry What would you like to see in terms of architecting this? I could manually set some of these things but I'm looking for advice on a more generic solution.

**Comment by davelandry** [comment]
Ok, this is what I'm thinking for new/modified props:

### `cutoff`
If the value is a _Number_, do the current behavior. If the user passes a _Function_, pass that function the full data list expecting it to return a filtered list. Pseudo-code example:

```jsx
cutoff: data => filteredData.filter(d => ["me", "nation", "similar1", "similar2"].includes(d.id))
```

### `cutoffText`

By default, it's `false`. 

Otherwise, show the text UNDERNEATH the collapsed bars (underneath the New York bar in your first screenshot) left-aligned to the already present right-aligned "Show More" button. Only show this text when the bars are collapsed.

```jsx
cutoffText: "Showing states with similar SIR."
```

### `sort`

This function determines the sort order of the bars in both collapsed and opened mode. It gets passed the data AFTER any `cutoff` function has been run. By default, it should be the current behavior (sorting by value). Pseudo-code override:

```jsx
sort: (a, b) => ["nation", "me"].includes(d.id) ? -1 : 1
```
