### ISSUE TITLE
[vizbuilder] remove "Empty Dataset" flash when loading

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#411]
Happens on page load:
1. "Empty Dataset" message displays
2. Then "Loading" appears

And when changing measures:
1. "Loading" appears
2. "Empty Dataset" message displays
3. "Loading" appears again

**Comment by frabarz** [comment]
The issue on page load is easy to solve, but when changing measures, there's a problem with the way the page is rendering.
The devtools network tab shows there's a new call to `/api/cubes/` after a measure changes, and if you look closely, the sticky header blinks for a moment, specifically when the permalink changes. This means the `<Vizbuilder />` component is being unmounted and mounted again, probably caused by the url update.
