### ISSUE TITLE
mailgun emails not pulling in translations

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/canon#424]
<img width="1537" alt="screen shot 2019-02-05 at 1 40 27 pm" src="https://user-images.githubusercontent.com/252276/52296344-1babad80-294c-11e9-8878-61bdd48c66ce.png">

I can see in this [activation email file](https://github.com/Datawheel/canon/blob/master/src/auth/emails/activation.html) that everything is wrapped in a `t()` function but for whatever reason these function dont seems to be pulling in the proper translations.

**Comment by alexandersimoes** [comment]
I have a hunch it's related to some env vars here: https://github.com/Datawheel/canon/blob/master/src/auth/local.js#L12-L24

**Comment by davelandry** [comment]
@alexandersimoes these links helped a lot, thanks for posting. Turns out the problem was when no language env vars were defined, the default internal canon-core localizations weren't used. In your case, in macro market, even though you have a `locales/en` file, it's not even being touched because you're not setting `export CANON_LANGUAGE_DEFAULT="en"`

The newest release should work for you, let me know if it doesn't.
