### ISSUE TITLE
[vizbuilder] treemaps and stacked area charts with too many data points hang the browser

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#454]
1. https://ulysses.datausa.io/visualize?groups=0-Z1DVCsC&groups=1-Z1XFeXX-11&measure=ALgX7
2. Change the Geography grouping to "County"
3. The loading screen appears, and then the animation hangs and nothing happens. The page breaks with no errors at the bottom of the screen.

@frabarz can you help debug this to see if it's a client-side or data-side issue?

**Comment by davelandry** [comment]
It looks like the cut doesn't even matter. You can remove it entirely and it still breaks just trying to load county data.

**Comment by frabarz** [comment]
the issue is caused by the stacked area chart, there are too many elements to render and the browser hangs
these are the urls of the individual charts:

- https://ulysses.datausa.io/visualize?enlarged=lineplot-j38kn&groups=0-j38kn&measure=ALgX7
- https://ulysses.datausa.io/visualize?enlarged=geomap-j38kn&groups=0-j38kn&measure=ALgX7
- https://ulysses.datausa.io/visualize?enlarged=treemap-j38kn&groups=0-j38kn&measure=ALgX7
- https://ulysses.datausa.io/visualize?enlarged=stacked-j38kn&groups=0-j38kn&measure=ALgX7

the first 2 render immediately, the treemap takes a bit more, but the stacked hangs the browser for a good while

following the conversation on slack, we are going to limit the visibility of treemaps with more than 1000 data points, and stacked area charts with more than 200 data points
