### ISSUE TITLE
[logiclayer] cut by several elements not working 

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#458]
Trying to filter by a specific interval of years `[2007, 2018]`, logiclayer returns the total of years `[2004, 2018]` availables in the cube.

Also, I noticed if you filter by a minor number of years (`&Year=2007,2008`) it works!

`api/data?drilldowns=Flow,Year&measures=Total&parents=true&Year=2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018&captions=en`

**Comment by cnavarreteliz** [comment]
@davelandry have you seen this bug? For Estonia I need to filter the data between years or months.

URL: [http://estonia.datawheel.us/api/data?drilldowns=Year&measures=Total&parents=true&Year=2012,2011,2010,2009,2008,2007,2006&captions=en&Flow=1](http://estonia.datawheel.us/api/data?drilldowns=Year&measures=Total&parents=true&Year=2012,2011,2010,2009,2008,2007,2006&captions=en&Flow=1)

**Comment by davelandry** [comment]
@cnavarreteliz the problem is that you have `Year` in your drilldowns. If you supply a cut for a dimension, it automatically applies the drilldown, but if you explicitly state the drilldown, it will return everything for that dimension. Try this query (you basically should never put `Year` in the drilldown list):

`/api/data?measures=Total&Year=2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018`
