### ISSUE TITLE
[vizbuilder] add tableLogic prop

### ISSUE THREAD

**Issue by jspeis** [Datawheel/canon#478]
When we show data at the state level in PUMS it should be enough so that we can default to using 1-year estimates

**Comment by davelandry** [comment]
This may need to be added as an external `prop` set by the user of the vizbuilder, similar to the logiclayer, because this behavior of "choosing the best version of the table" can be different for every data source/project.

@frabarz what do you think about adding a new prop to the `Vizbuilder` component called `tableLocic`, where IF the viz builder identifies tables with the same `table_id` annotation, it runs this function to allow the user to pick which one to use. I could see it accepting the cubes and the current query as arguments:

```jsx
tableLogic={(cubes, query) => {
  return cubes.find(d => d.name.includes("_5")) || cubes[0];
}}
```

That's just a pseudo-code example of the logic. What is the current internal logic, just pick the first cube in the array?

**Comment by frabarz** [comment]
Is a good implementation, not too complicated.
By default it currently just finds the first measure that matches by name, and that depends on the order the cubes come from the server.
From the slack thread we decided to keep it that way if there's no function passed to `tableLogic`.
