### ISSUE TITLE
unable to add a previously present grouping

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#509]
from Cesar:
https://preview.datausa.io/visualize?groups=0-1LK22m&groups=1-2rAHKG-2&groups=2-ZJJp1G-4411&groups=3-Z5TtG5-2&measure=ZkH9RT
> If I click on "Delete" on one of the group bys (e.g. the Industry) I cannot add it again.

**Comment by frabarz** [comment]
This issue was caused by the grouping limit we implemented a few weeks ago.
As I [mentioned in the issue](https://github.com/Datawheel/canon/issues/498#issuecomment-478088966), using a crafted permalink (like the ones in the example visualizations view) you can add as many groupings as you want, but from the UI pov the user is still limited by the value set in `groupLimit`.
