### ISSUE TITLE
[cms] refactor topic endpoint for global filters

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#516]
The process should be as follows:
- [x] refactor the topic endpoint to receive the generator values from the client
- [x] return the entire new profile payload from the endpoint
- [x] refactor the front-end components to utilize this global payload

**Comment by jhmullen** [comment]
@davelandry Now that selectors ultimately belong to profiles, and this topic endpoint now is returning the entire profile, is there even a need for a topic endpoint at all?

I get the feeling it would be sufficient to add some query params to the existing profile endpoint - one that allows you to provide the variables object, and the rest just being whatever states the (again, now profile-wide) drop-downs are in.

Does this sound correct?

**Comment by jhmullen** [comment]
In doing a little more thinking, I've realized we do use the topic endpoint for permalinks/embeds - but even this would just be the topic endpoint in its **current state**, that is, one that needs to calculate everything from scratch, and returns ONLY the topic itself (not the entire profile).

So I'm thinking the direction should be:

- Leave the topic endpoint as-is, for fully-calculated embeds.
- Upgrade the profile endpoint to allow for providing the variables obj and all dropdown states.

**Comment by davelandry** [comment]
@jhmullen I kind of like the idea of combining them into 1 single endpoint. Is there any benefit to keeping them separate?

**Comment by jhmullen** [comment]
@davelandry The only benefit I can see is the "topic-embed" case - where we truly only want to return one topic.  We could handle this with another param, `&topicID=123`, which is just a special case to tell the unified endpoint to only return one topic?

**Comment by davelandry** [comment]
@jhmullen I like that! let's do that! Maybe simpler though? `&topic=123`

**Comment by davelandry** [comment]
Just make sure it works with the topic SLUG as well (as it currently does/should)

**Comment by jhmullen** [comment]
Closing this, with a few notes to myself, to eventually move to the release notes:

There is now a single unified `/api/profile` endpoint, which receives all options via query parameters.

The usual way of retrieving a profile via GET, with a list of slug/id pairs, remains the same: `/api/profile?slug1=geo&id1=Massachusetts&slug2=cip&id2=Metalworkers`.

However, a POST endpoint has been added at the same endpoint, `/api/profile`, with the following properties:

- The user must provide their own `variables` object in the post - the one that they received on page load.
- The user may directly use the profile id (for the full profile to be returned) or the topic id (for just a single topic for embeds) as a query param instead of the slug/id pairs, as the variables have already been calculated.  This is done with `&profile=<id>` or `&topic=<id>`.

So if the user changed a dropdown on the page, the new profile request might look like this (pseudocode):

```
const {variables} = this.state  // saved from initial load
const {id} = this.state.profile   // saved from initial load
const {someSelectorState} = this.state;   // received from onSelector change
const selectorString = makeQueryParamsFrom(someSelectorState);
const url = `/api/profile?profile=<id>&${selectorString}`;
const payload = {variables};
axios.post(url, variables).then(resp => this.setState({profile: resp.data});
```

**Comment by jhmullen** [comment]
Sorry, re-opening this, to eventually be closed when the PR is merged.
