### ISSUE TITLE
[cms] switch Options location to use router

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#537]
The redux store instance of `location` is always the initial server-rendered location, but will be incorrect for subsequent page views done client-side using react-router links. This causes the share URL to be incorrect after the first page load.

- [x] use `this.props.router.location` for all instances of `location` in render
- [ ] ~remove the connection to the redux store for `this.props.location`~

**Comment by perpetualgrimace** [comment]
@davelandry `this.props.router` is returning `undefined` in this component. 🤔

**Comment by davelandry** [comment]
as just discussed in person, `this.context.router` in combination with adding the appropriate `contextTypes` should get you there!

**Comment by perpetualgrimace** [comment]
@davelandry okay I got a bit further, but `this.context.router.location` isn't giving me as much information as the redux state `router.location`. It seems I'm only able to get the pathname (i.e., `"profile/country/fi"`) rather than the entire URL. Should I get the `origin` from redux and combine it with the pathname from context?

**Comment by davelandry** [comment]
@perpetualgrimace ahhh intereseting. If it's not providing `origin`, then it's okay to use that `origin` from Redux (the origin, or base of the URL, won't ever change in react-router land)
