### ISSUE TITLE
[cms] multiple chart updates when I scroll in profile page

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#544]
I've been experimenting a weird issue, when I scroll in DataEstonia [https://data-dev.stat.ee/profile/partner/be?locale=et](https://data-dev.stat.ee/profile/partner/be?locale=et), it seems the visualization is reloading multiple times
![multiple](https://user-images.githubusercontent.com/5233593/58663196-fa573e80-82f9-11e9-8aa6-551952655222.gif)

**Comment by davelandry** [comment]
@cnavarreteliz my guess is that this is caused in Estonia because you are using `forceUpdate`: https://github.com/Datawheel/data-estonia/blob/ace7e3befcf598b505738785ff2b04b4b7e75100/app/components/Chart.jsx#L397

The `forceUpdate` property should really only be used in debugging purposes, as it means "re-render this React component any time the react-dom is refreshed", so that mean that charts will re-render even if the config has not changed at all (the default logic will only re-render the viz when the stringified versions of the old and new config do not match)

**Comment by cnavarreteliz** [comment]
@davelandry but the URL that I'm posting is from `Profile` component, that doesn't using `Chart.Component` in either case.

**Comment by davelandry** [comment]
Hmm, ok. I don't have a local environment for estonia set up, so can you go into your local node_modules directory and add some console.logs into d3plus-react to see why it's updating? Specifically here: https://github.com/d3plus/d3plus-react/blob/master/src/Viz.js#L38

**Comment by cnavarreteliz** [comment]
Hmmm, I can't reproduce the bug, I included `console.log`, but it doesn't reloading at `d3plus-react` level
