### ISSUE TITLE
[cms] add "sticky" toggle for sections

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#563]
- [x] new db column
- [x] toggle in section builder (the new [Switch](https://blueprintjs.com/docs/#core/components/switch) component?)

**Comment by jhmullen** [comment]
@perpetualgrimace This is in the `feature-toolbox` branch and ready to be styled

**Comment by perpetualgrimace** [comment]
Went with a button group for the toggle. The available iconography is a little fuzzy for this concept, but I think these alignment icons work well enough (especially given that there is a text label):

<img width="590" alt="Screen Shot 2019-07-02 at 12 27 29 PM" src="https://user-images.githubusercontent.com/6193798/60529576-e15cf700-9cc4-11e9-9fad-0e389bf5d69f.png">

Okay so a few questions about implementing this in profile sections:

1. For which client/project is this for? Asking because I'd like to use `position: sticky`, which is well supported, and sticky sections will simply fall back to not being sticky at all in IE. But if the client wants to see this feature in IE, we'll need to polyfill it.

2. How do I get access to the sticky setting within `Profile.jsx`?

**Comment by jhmullen** [comment]
Moved @perpetualgrimace 's task to #577
