### ISSUE TITLE
[cms] Implement Front-end support for sticky sections

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#577]
CSS/JS in abstract `Section` class (@perpetualgrimace):   - sticks to top of page when it hits it   - moves off of top when the next sticky section replaces it

**Comment by perpetualgrimace** [comment]
Okay so a few questions about implementing this in profile sections:

For which client/project is this for? Asking because I'd like to use position: sticky, which is well supported, and sticky sections will simply fall back to not being sticky at all in IE. But if the client wants to see this feature in IE, we'll need to polyfill it.

How do I get access to the sticky setting within Profile.jsx?

**Comment by davelandry** [comment]
@perpetualgrimace CDC is asking, so they def need IE 10 support 😓 

Sticky setting within Profile.jsx? I'm thinking: 
- add the JS detection into `/packages/cms/src/components/Profile.jsx`
- that logic detects which member of `this.state.profile.sections` should be sticky
- the current "`stickySection`" gets saved to Profile state, and passed down via context
- Sections subscribe to that context and determine if the should be sticky
