### ISSUE TITLE
[cms] allow toolbox to be collapsed

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#717]

**Comment by davelandry** [comment]
@perpetualgrimace I'm curious if there's a way to redesign that sidebars so that you don't need to open/close an entire panel when you want to change sections. Maybe something like a blueprint [`OverflowList`](https://blueprintjs.com/docs/#core/components/overflow-list) but with pop-up menus to allow switching between sections?

**Comment by perpetualgrimace** [comment]
Man this is a really tough problem, because the tree is already super overloaded (it's for navigation, as well as adding/removing/reordering sections). 

But we do have the header component with the title now, so I can look into improving that with some navigation solutions like the one you suggested.

Maybe the tree is better off living in an absolutely positioned drawer? That way it wouldn't shuffle the page around when toggling it open/close. 🤔

I think coming up with a good solution for this will involve some explorations in sketch.
