### ISSUE TITLE
[cms] store setVariables in query arguments of Profile

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#724]

**Comment by davelandry** [comment]
@jhmullen is this now done with v0.14?

**Comment by jhmullen** [comment]
Technically, no. Only selectors have been hooked up to query args. Arbitrary calls of `setVariables` are not storing their states in params.

However, I can and will add this, and use this issue to track it.

**Comment by jhmullen** [comment]
Revisiting this, it seems like a good idea, in particular because it allows for shareable links that respect viz state. However, I'm concerned about users being able to inject variables into the page, because in certain circumstances it could be used to circumvent the paywall. 

The nice thing about selectors is that I can guarantee that the query args are valid selectors. 

This could be accomplished if variables could be marked as acceptable (or unacceptable) for query-arg use. Or, if I could somehow detect, via the on-click code, which variables should be allowed to be query-ized. Otherwise, someone could change their pro status variable via the URL.

Thoughts, @davelandry ?

**Comment by davelandry** [comment]
Hmm, this is a super interesting case, good catch @jhmullen about that possibility to override variables users shouldn't be able to override.

I could see this solution: just like a CMS contributor creates generators/materializers/selectors, allow them to create "variables" (or whatever it should be called), that essentially registers a given string as an allowed "global variable" to be set by page interaction.

**Comment by jhmullen** [comment]
Closing this, as the complexity of attaching alloweds to global variables etc is not in scope for the sunsetting CMS. Will revisit in 1.0
