### ISSUE TITLE
[cms] horizontal profile tree refactor

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#726]
blocked by #725

**Comment by perpetualgrimace** [comment]
Made some headway this week.
![horizontal-nav-progress](https://user-images.githubusercontent.com/6193798/68515049-a7d96100-024d-11ea-97b6-d7eba0b69696.gif)

**Changes made**:
- The tree is now horizontal (I'm calling it an outline)
- The name of the current entity (i.e., "geo / hai profile") is now shown in the top left
- You can click the entity title to collapse or show the outline
- The main nav on the right now includes dropdowns for selecting profiles, or creating new ones
- On small screens, a menu button is shown next to the settings button, allowing you to toggle the main nav visibility
- When you choose a section, the section is highlighted in the outline
- When you hover a section for approximately a second, a contextual menu appears to the right with buttons for adding a new section and reordering sections

**TODO/HALP**:
- Add story section switching
- Add ribbon hierarchy using grouping sections (😬😬😬)
- Use redux dispatch for page/section switching (currently they're just links; see my `profileNavItems` array)
- The edit entity gear icon should link to the Profile/Story edit view for now, since clicking the entity name collapses/shows the outline. See `toggleEntitySettings()` placeholder function.
- The create new profile button in the profile nav dropdown should create a new profile and navigate to it. See `createProfile()` placeholder function.
- The add section button should add a new section by clicking button adjacent to the hovered section node. See `createSection()` placeholder function.
- The swap sections button should reorder two adjacent sections by clicking the button adjacent to hovered section node. See `swapSectionsPosition()` placeholder function.
- Probably should move a bunch of logic out of render
- Probably should split up Nav into smaller components
