### ISSUE TITLE
[cms] profile search endpoint

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#875]

**Comment by alexandersimoes** [comment]
Here's my braindump from the wednesday lunch and learn:

Deep search will expose a series of endpoints (pre-seeded) with all dimensions available in the cubes AND with their slugs scraped from the CMS search table. The following are a few sample endpoints and responses:

`/deepsearch/oec/api/v1/search?query=Orange&min_confidence=.42`

<img width="300" alt="Screen Shot 2019-12-16 at 6 29 29 PM" src="https://user-images.githubusercontent.com/252276/70951702-1b7f4280-2032-11ea-8387-36fa1068c331.png">


`/deepsearch/oec/api/v1/search?query=Exports%20of%20Peru%20to%20Brazil&min_confidence=.42`

<img width="428" alt="Screen Shot 2019-12-16 at 6 29 53 PM" src="https://user-images.githubusercontent.com/252276/70951710-21752380-2032-11ea-915c-5854e6c28008.png">

The response of the canon endpoint will then need to loop over all of the results and tie them in with the available profiles (that it knows from the CMS) to create a payload of results.

These results should be returned in one of two ways (depending on a flag):
1. All results combined (this will be helpful for things like the homepage search and top right nav search)
2. Grouped results (this will be the results above but grouped by their profile type)

**Comment by MarcioPorto** [comment]
Examples for displaying factoid queries:

- https://docs.google.com/drawings/d/1TCUFA65IsSxy2NRXGPKghV4A-IxdY41GJ6LRVLEeHe4/edit
- https://docs.google.com/drawings/d/1Us2R0TnjBd97r7wywprS2LA0kF-yDa9hOO62ZChfk2A/edit

**Comment by jhmullen** [comment]
@davelandry 

The branch `issue-875-deepsearch` contains updates to searchRoute.js, adding a `/deepsearch` endpoint to marcio's current hercules installation.

I have made a new component, DeepSearch.jsx, which is the currently unstyled stub that would eventually become the Search Component that ships with Canon.  It has been added to routes.jsx via DeepSearchPage.jsx for testing.

I am tagging you here to loop you in on the upcoming design work that will be needed to get this Search component into OEC. James indicated that much of the design work needed for this Canon CMS search component has already occurred in OEC and will require porting.

I am still working on this branch (documentation, sorting improvements, etc) but want to loop you in sooner rather than later - The faster we can get this into OEC so people can use it and find out what is broken, the faster I can iterate and develop the algos with Marcio.
